feat: adds reusable workflows for cra
ornio-no/common-workflows pull request #15
Opened 2021-12-07 15:39 UTC by fitimbyttyqi

[issues-28/cra-reusable-actions](https://github.com/ornio-no/issues/issues/28)

2021-12-07 15:42 UTC, fitimbyttyqi commented
@oxodesign I need to make further tests with cra reusable workflows, tomorrow we could make a meeting or maybe give me access to merge instead of waiting for you because you are busy to always make approves.
If we keep a meeting I would like to know some things with im unclear with regarding the setup with cra applications

2021-12-07 18:36 UTC, oxodesign commented on .github/workflows/cra-build.branches.yml
> +name: CRA Build Branches
@fitimbyttyqi ❌ file name should be cra-build-branches.yml (you have a . instead of -)

2021-12-07 18:37 UTC, oxodesign requested changes
@fitimbyttyqi ❌ minor file name issue, see the comment otherwise great job :)

2021-12-08 08:08 UTC, fitimbyttyqi commented
@oxodesign Done :)

2021-12-08 08:40 UTC, oxodesign approved these changes

2021-12-08 08:40 UTC, merged